# Generated by Django 4.2 on 2024-02-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_review_to_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_dispute_written',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_review_written',
            field=models.BooleanField(default=False),
        ),
    ]
